name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Update dependencies
        run: |
          bun update --latest
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update dependencies
          title: 'chore: update dependencies'
          body: |
            This PR updates project dependencies to their latest versions.
            Please review the changes and merge if everything looks good.
            
            Changes made in the core directory.
          branch: auto-dependency-update
          base: ${{ github.head_ref }}
          path: ./core
          delete-branch: true
          
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Notify if no updates
        if: steps.git-check.outputs.changes != 'true'
        run: |
          echo "No updates were found this time :). have a good day..."