name: Update Core Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-core-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Update Dependencies in Core
        working-directory: ./core
        run: |
          bun update --save
          
      - name: Verify Updates
        working-directory: ./core
        run: |
          echo "Updated dependencies in 'core' folder:"
          cat bun.lockb || echo "No lockfile found. Update may not have persisted"
