name: let it happen

on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  update-core-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: repo in check
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup bun because why not?
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: clean workspace
        run: |
          git clean -fdx
          git reset --hard HEAD

      - name: clear bun cache
        run: bun cache clean

      - name: update dependencies in core
        working-directory: ./core
        run: |
          export NODE_OPTIONS=--max-old-space-size=4096
          bun update --latest
          bun install --silent --no-save

      - name: commit and push changes
        working-directory: ./core
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json bun.lockb
          git commit -m "chore: update dependencies in core folder"
          git push origin HEAD
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}