name: the less i know, the better

on:
  schedule:
    - cron: '0 0 1 1 *'
  
jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - name: intothelmao
        uses: actions/checkout@v3

      - name: change the year
        run: |
          CURRENT_YEAR=$(date +"%Y")
          sed -i "s/Copyright (c) [0-9]\{4\}/Copyright (c) $CURRENT_YEAR/" LICENSE
          
      - name: lmao
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: do changing
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add LICENSE
          git commit -m "Update license year to $CURRENT_YEAR"
          
      - name: and there it is
        if: steps.git-check.outputs.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}